spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        #todo

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG

