\connect menu_dishes;

-- hash generated by https://bcrypt-generator.com/
-- username = frosty, password = ytsorf, role = MANAGER, OBSERVER
INSERT INTO users (username, password)
VALUES (
    'frosty',
    '$2a$12$9S/52rqhTd6uCujg5TGF3.jEFdbMXdGDfx2IYUDk.4oADRCoWd/LW'
);

INSERT INTO user_roles (user_id, role)
SELECT u.id, 'MANAGER'
FROM users u
WHERE u.username = 'frosty';

INSERT INTO user_roles (user_id, role)
SELECT u.id, 'OBSERVER'
FROM users u
WHERE u.username = 'frosty';

-- username = observer, password = observer, role = OBSERVER
INSERT INTO users (username, password)
VALUES (
    'observer',
    '$2a$12$6/O6kjPTw7gvd5Ccf037PeK05Uba6mksuhgQch6agI/Q/V3qq7xAO'
);

-- username = waiter, password = waiter, role = WAITER
INSERT INTO users (username, password)
VALUES (
    'waiter',
    '$2a$12$bcfwc0gJ5WOVIw01ZKlLyOt2dyIWb7882WWnUc55hQD4tDIQp.LZG'
);

INSERT INTO user_roles (user_id, role)
SELECT u.id, 'WAITER'
FROM users u
WHERE u.username = 'waiter';

-- username = manager, password = manager, role = MANAGER
INSERT INTO users (username, password)
VALUES (
    'manager',
    '$2a$12$zrKgDkNc0.OcT4zOmxtsVOjLDKtgECaUHLBiDahzw/te0r4pS.BBy'
);

INSERT INTO user_roles (user_id, role)
SELECT u.id, 'MANAGER'
FROM users u
WHERE u.username = 'manager';

-- username = service, password = service, role = SERVICE
INSERT INTO users (username, password)
VALUES (
    'service',
    '$2a$12$daOKSmHslWEYeFEi5n3O8udIWaNrEpQNMOjDlnEKX1VABl9P9y9mu'
);

INSERT INTO user_roles (user_id, role)
SELECT u.id, 'SERVICE'
FROM users u
WHERE u.username = 'service';