spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6767/menu_dishes
    username: frosty
    password: restaurant
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

service-auth-credentials:
  username: service
  password: service

logging:
  level:
    at.frosty.restaurant: TRACE
    #org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, mappings, httptrace